### ISSUE TITLE
GitHub Actions update?

### ISSUE THREAD

**Issue by zeileis** [alexpghayes/distributions3#102]
Alex @alexpghayes, I haven't worked much with GitHub Actions myself so I might be wrong about this but my impression is that the GitHub Actions for `distributions3` are somewhat outdated and hence do not work properly anymore.

In the `R-CMD-check.yaml` only the `{os: windows-latest, r: 'release'}` seems to work properly. I'm not sure what needs to be changed to make the other flavors work. Or we could reduce the number of flavors which would be also good, I think.

The `pkgdown.yaml` also does not work at the moment. For another package I'm involved in we switched to the `v2` version of the workflow (https://github.com/zeileis/ivreg/blob/main/.github/workflows/pkgdown.yaml) but I didn't check whether this is still the current recommendation.

What do you think we should do about this?

**Comment by alexpghayes** [comment]
Should be back up and running now

**Comment by zeileis** [comment]
Merci! :tada:
