### ISSUE TITLE
simulate.default()

### ISSUE THREAD

**Issue by alexpghayes** [alexpghayes/distributions3#103]
@zeileis why does `simulate.default()` exist? It seems like `simulate.distribution()` should be sufficient as a wrapper for `random()`, no?

**Comment by alexpghayes** [comment]
Nvm I can't read

**Comment by zeileis** [comment]
No worries.

But this new default method is really nice because it is now easy to do parametric bootstrap stuff for all the model classes that cooperate with `distributions3`.
