### ISSUE TITLE
pdf/cdf/quantile should error if x is outside of domain.

### ISSUE THREAD

**Issue by EmilHvitfeldt** [alexpghayes/distributions3#22]
An error is thrown, but it is happening inside dbinom which is non-ideal. 0 is returned but should ideally be errored.

``` r
library(distributions)

pdf(Bernoulli(0.1), 0.5)
#> Warning in dbinom(x = x, size = 1, prob = d$p): non-integer x = 0.500000
#> [1] 0
```

<sup>Created on 2019-06-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by EmilHvitfeldt** [comment]
Similar arguments can be make for x is outside [0, 1] in the case of the Bernoulli.

``` r
library(distributions)

pdf(Bernoulli(0.1), -12)
#> [1] 0
```

<sup>Created on 2019-06-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by alexpghayes** [comment]
I think this behaviors are basically correct, or at least correct enough for now.
