### ISSUE TITLE
Interest in extreme value distributions?

### ISSUE THREAD

**Issue by njtierney** [alexpghayes/distributions3#35]
I recently learnt about the package, [evd](https://cran.r-project.org/web/packages/evd/index.html), which provides extreme value distributions - would you be interested in adding a few of the key distributions from this? E.g., Fréchet and Gumbel?

**Comment by alexpghayes** [comment]
I would be thrilled to support these distributions! At the moment, I don't have enough bandwidth to do this myself, but I am happy to review a PR!

**Comment by njtierney** [comment]
Functions to look into implementing: 

# First steps

- [ ] `frechet` distribution
- [ ] `gumbel` distribution
- [ ] `rweibull` distribution

# generalised distributions?

- [ ] `gev` (generalised extreme value) distribution
- [ ] `gpd` (generalised pareto) distribution
- [ ] Bivariate Extreme Value Distributions?
- [ ] extreme? takes in some function of density, distance, etc,

**Comment by alexpghayes** [comment]
Closing since this seems like it has probably gone stale. I am working on getting a new CRAN release out this winter, so if you'd like to get this stuff in, now is the time to revive old PRs, etc, etc.
