### ISSUE TITLE
Name conventions

### ISSUE THREAD

**Issue by alexpghayes** [alexpghayes/distributions3#4]
- Distribution as capital letters?
- `_stat` / `_obs` suffix for observed values of statistics

Try to follow upper/lower-case convention to make things look as much like the math in textbooks as possible

**Comment by alexpghayes** [comment]
- `p` vs `pi` vs `prob` for probabilities -- use `p` -- make sure documentation uses this as well

**Comment by 1danjordan** [comment]
I kind of like the idea of using capitals for the distribution constructor - it matches how a distribution is written in a book and also is a nod towards object creation. 

```r
n <- Normal()
random(n, 100)
``` 

Although, I'm fairly indifferent - I just think it might have some merits.

Some others that have come up - `trials` vs `size` in the binomial. `experiments` for the number of repeated experiments in the binomial. Using `scale` versus `rate` in the exponential.

**Comment by alexpghayes** [comment]
Hmmm I've been thinking about that as well. I'm realizing I like capital letters for random variables themselves:

``` r
X <- Binomial(10, 0.5)
Y <- Normal(0, 1)
```

**Comment by 1danjordan** [comment]
Oh yeah, I like how that reads too

**Comment by 1danjordan** [comment]
This just crossed my mind... We could use a formula to make it *really* look like a stats book

```r
X ~ Normal(0, 1)
```

I'm not sure how it would be used though, because you'd still have to use assignment if you want to reuse the distribution.

```r
random(X ~ Normal(0, 1), 100)
# or not so nice
x <- X ~ Normal(0, 1)
random(x, 100)
```

I don't think it really works but it's such tempting syntax.

**Comment by EmilHvitfeldt** [comment]
>  such tempting syntax

It sure is! I made a solution! (I doubt it would be a good idea)

if we give all the distribution functions a `distribution` class, then we can redefine ~ to do assignment when the RHS is a distribution and work like normal when it isn't.

``` r
library(distributions)

Normal <- function (mu = 0, sigma = 1) {
    d <- list(mu = mu, sigma = sigma)
    class(d) <- c("normal", "distribution")
    d
}

`~` <- function(x, y) {
  if ("distribution" %in% class(try(y, silent = TRUE))) {
    assign(deparse(substitute(x)), y, pos = 1)
  } else {
    return(as.formula(paste(deparse(substitute(x)), deparse(substitute(y)), sep = "~"),
                      env = parent.frame()))
  }
}

X ~ Normal(0, 1)

X
#> normal distribution (mu = 0, sigma = 1)

Y ~ X
Y
#> normal distribution (mu = 0, sigma = 1)

mpg ~ disp + vs
#> mpg ~ disp + vs
```

<sup>Created on 2019-06-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by 1danjordan** [comment]
Oh wow this is deadly 🤩 There is something very attractive about it... 

I was thinking a `distribution` subclass would be a good idea for having a something functions can fallback on, but didn't have any concrete examples to justify it. But here's a clear one.

**Comment by alexpghayes** [comment]
@EmilHvitfeldt that is immensely clever and also horrifying.

@1danjordan A `distribution` subclass is definitely a good idea.

On the whole, however, I am opposed to the syntax. Not because it isn't useful, but because it requires metaprogramming, and metaprogramming is not beginner friendly. Teaching stat 101 about one assignment operator is hard, and teaching them about two different assignment operators, one of them an occasional quoting operator, would probably be too much.

Lord though that is cool

**Comment by EmilHvitfeldt** [comment]
Full support, I didn't really think it should be used. I just couldn't ignore the challenge of making it work

**Comment by 1danjordan** [comment]
Small point on the move to capitalised distriubtion names - `Gamma()` already in the `stats` package. Also, what do you want to do for `log_normal` and `fisher_f`? `LogNormal` and `FisherF`?

**Comment by alexpghayes** [comment]
I think we should do `Gamma` for consistency even though there will be conflict. We should include a note about this, and examples of namespacing to get each version, in the documentation. And yeah, like I `LogNormal` and `FisherF`!
