### ISSUE TITLE
quantile() masks stats::quantile()

### ISSUE THREAD

**Issue by rmtrane** [alexpghayes/distributions3#58]
This is no surprise, as it is even mentioned on the help page. 

Problem: geom_qq_line() will not work while distributions3 is loaded. This is an issue if you (like me...) would like to use distributions3 and ggplot2 for teaching without having to touch the base R plotting functions, and are forced to cover QQ-plots... An ad-hoc fix is to use geom_abline() instead of geom_qq_line(), but it adds an unwanted and unnecessary extra level of complexity.

I have no fix for this, but think it would be worth it to find a way around it down the line, if possible.

**Comment by rmtrane** [comment]
This is actually turning into a bigger problem for me than originally anticipated: when creating a bootstrap CI, for example, one would like to be able to do `quantile(t_hats, 0.025)`, which won't work if `distributions3` is loaded. It is not super satisfying having to tell students to remove the package, or use `stats::quantile`. 

@alexpghayes @paulnorthrop Any thoughts on a quick, but not too dirty, fix?

**Comment by alexpghayes** [comment]
distributions3::quantile() is a generic, so if the first argument isn't a
distribution object you could default to stats::quantile(). Something like

quantile.default <- stats::quantile()

instead of an error

**Comment by rmtrane** [comment]
Beautiful! Works like a charm. Thank you!

**Comment by alexpghayes** [comment]
Did this ever make it into `master`?

**Comment by rmtrane** [comment]
Not that I'm aware of.
