### ISSUE TITLE
pareto distribution

### ISSUE THREAD

**Issue by softloud** [alexpghayes/distributions3#6]
Love the idea of this package :+1:. 

I often need the Pareto distribution, for which I use `actuar::*pareto2`. Is it a barrier that this distribution isn't provided in base? Or could it also be incorporated?

**Comment by alexpghayes** [comment]
Not at all. Why don't you wrap it and list `actuar` in `Suggested`?

Down the line it'd like to implement the samplers internal in C++, but to get started I thinking wrapping existing implementations is a good idea.

**Comment by softloud** [comment]
I am learning about dependencies, too, atm - cheers, this is very enlightening!

**Comment by alexpghayes** [comment]
Closing since at some point we got a `GeneralizedPareto`
