### ISSUE TITLE
Use Distributions.jl test reference file for verification of distributions3

### ISSUE THREAD

**Issue by 1danjordan** [alexpghayes/distributions3#62]
Distributions.jl uses a reference file to verify correctness of their implementation. Surprisingly, they also have a [practically complete R package](https://github.com/JuliaStats/Distributions.jl/blob/master/test/ref/discrete_test.ref.json) in R6 they used to create this reference file. See the reference files for [discrete distributions](https://github.com/JuliaStats/Distributions.jl/blob/master/test/ref/discrete_test.ref.json) and [continuous distributions](https://github.com/JuliaStats/Distributions.jl/blob/master/test/ref/continuous_test.ref.json).

We could leverage their reference file to use in verifying `distributions3`, in a similar manner to how they do so. This would require a bit of code to map each distribution in `distributions3` to the entry in each JSON file. I think this would be more robust and (once written) accelerate development/introduction of new distributions because the test would essentially already be written!

**Comment by alexpghayes** [comment]
👀👀👀 !!

**Comment by 1danjordan** [comment]
I think simplest solution is to just copy the files over and rename the distributions to match the names of our distributions. It won't be reproducible, but can clearly document. The reference files haven't been updated for 3 years, so I don't think it's worth the time to ensure full reproducibility right now. 

Being locked at home, I've found the time to work on `distributions3` some more. Will start working on a PR.

**Comment by alexpghayes** [comment]
Closing this unless something wants to actively work on it.
