### ISSUE TITLE
Revised CRAN release

### ISSUE THREAD

**Issue by ResearchActuary** [alexpghayes/distributions3#64]
Are there plans for a CRAN release that will include some of the bug fixes that have been implemented? If it matters, I'm thinking of https://github.com/alexpghayes/distributions3/pull/51 specifically. I have a package, `imaginator` which uses `distributions3` that I'm preparing for a CRAN update.

**Comment by alexpghayes** [comment]
@rmtrane Do you know if anyone is going to use this to teach in the fall? Would love to find someone else to make a release happen if possible

**Comment by rmtrane** [comment]
I do not know of anyone else, but do plan on using it again myself. Would love to help to make this happen.

**Comment by alexpghayes** [comment]
Closing in favor of #70
